# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate a double-sided normal selectivity curve for a length vector
#'
#' Slightly faster C++ version.
#' A double-sided normal takes two separate slope (sigma^2) parameters
#' around the mode parameter (mu) that change the slope independently
#' on either side of the mode. The selectivity varies from 0 to 1.0,
#' with 1.0 being at the mode. It is calculated for each position defined
#' in the length vector. Setting the second slope parameter (Ss2) to zero
#' creates a flat-top selectivity.
#'
#' @param  LMP  A vector of lengths (usually mid-points for length bins)
#' @param  Smx  Mode of the normal selectivity function
#' @param  Ss1  Left side slope, parameterized as 1/sigma^2
#' @param  Ss2  Right side slope, parameterized as 1/sigma^2. Zero implies
#' flat-topped selectivity
#' @return      A vector of selectivity values varying from 0.0 to 1.0
#' @noRd
#'
Csel_dsnormal <- function(LMP, Smx, Ss1, Ss2) {
    .Call(`_fishblicc_Csel_dsnormal`, LMP, Smx, Ss1, Ss2)
}

#' Calculate the survival of a fish cohort to sequential length boundaries
#'
#' This C++ version of the `RSurvival_Est()` function.
#' The model integrates over growth rate variability and sums mortality
#' piece-wise over intervening length intervals to derive the
#' survival to each length bin boundary taking into account variation in growth
#' and varying mortality-at-length. This is analogous to an age based catch
#' curve model, but for length. Survival can be used to estimate population
#' numbers-at-length and catch length frequency, among other things.
#' The model uses the Gauss-Laguerre quadrature rule for integration,
#' so nodes and weights for this must be provided.
#'
#' @param  node   Nodes for the Gauss-Laguerre quadrature rule
#' @param  wt     Weights for the Gauss-Laguerre quadrature rule
#' @param  Len    Vector of lower-bounds for length intervals
#' @param  Zki    Vector of total mortality (in time units of growth rate
#' parameter K) to be applied in each length interval.
#' This vector should be the same length as Len.
#' @param  Galpha Alpha parameter for the Gamma probability density function
#' that governs growth variability.
#' @param  Gbeta  Beta parameter for the Gamma probability density function
#' that governs growth variability.
#' @return A vector of proportion surviving to each length bin lower bound.
#' @noRd
#'
CSurvival_Est <- function(node, wt, Len, Zki, Galpha, Gbeta) {
    .Call(`_fishblicc_CSurvival_Est`, node, wt, Len, Zki, Galpha, Gbeta)
}

#' Calculate the population relative numbers-at-length within length bins
#'
#' C++ Version of the `RNinInterval()` function.
#' The relative numbers in each length bin is based on the definite integral
#' over the bin growth transition time:
#'     N_i = (S_i - S_{i+1})/Z_{ki}
#'
#' @param  surv Survival to the lower boundary of each length bin
#' (see `RSurvival_est`)
#' @param  Zki  Total mortality within each bin (time in units of the
#' growth rate K)
#' @return A vector of relative numbers of fish within each length bin.
#' @noRd
#'
CNinInterval <- function(surv, Zki) {
    .Call(`_fishblicc_CNinInterval`, surv, Zki)
}

