# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Csel_dsnormal <- function(LMP, Sm) {
    .Call(`_fishblicc_Csel_dsnormal`, LMP, Sm)
}

Cpop_len <- function(node, wt, Len, Zki, Galpha, Gbeta) {
    .Call(`_fishblicc_Cpop_len`, node, wt, Len, Zki, Galpha, Gbeta)
}

